### ISSUE TITLE
Roccat Kain 100

### ISSUE THREAD

**Issue by 1928821929** [clicksounds/indexer#16]
### Add Pack

[RoccatKain_ONEHUNDRED.zip](https://github.com/clicksounds/indexer/files/14858911/RoccatKain_ONEHUNDRED.zip)

**Comment by coopeeo** [comment]
@1928821929 you need a pack.json. please look at the zip file in the indexer repo. or [download here](https://github.com/clicksounds/indexer/raw/main/Click_Sound_Template.zip)

**Comment by coopeeo** [comment]
e
