### ISSUE TITLE
Zoink Clicks V2 (Randomized)

### ISSUE THREAD

**Issue by GDBitah** [clicksounds/indexer#22]
### Add Pack

zoink randomized clicks

[bitah.zonk-click-pack-(randomized).zip](https://github.com/user-attachments/files/18277204/bitah.zonk-click-pack-.randomized.zip)

**Comment by BeatACVR** [comment]
was this made with the pack generator?

**Comment by MuhXd** [comment]
!accept

**Comment by BeatACVR** [comment]
there's nothing called test/yessir in that zip

**Comment by MuhXd** [comment]
no it makes test/yessir.zip

**Comment by MuhXd** [comment]
the pack has been added so you can close it

**Comment by MuhXd** [comment]
oh yeah the id is bitah.zonk-click-pack
@GDBitah

**Comment by GDBitah** [comment]
> there's nothing called test/yessir in that zip

I used the generator.
