### ISSUE TITLE
Add this narduar clickpack pwease

### ISSUE THREAD

**Issue by joshhussinblurd** [clicksounds/indexer#25]
### Add Pack

[exparaigon.normiepack.zip](https://github.com/user-attachments/files/18278753/exparaigon.normiepack.zip)

**Comment by joshhussinblurd** [comment]
Man of this works I'm cooked

**Comment by joshhussinblurd** [comment]
!accept

**Comment by coopeeo** [comment]
THEY DID NOT LOL
[
![IMG_2148](https://github.com/user-attachments/assets/739312d1-996c-4d7f-8a95-944a634e3499)
](url)

**Comment by coopeeo** [comment]
one sec testing something
```json
{}
```

**Comment by uniqeguyski** [comment]
Lemme borrow your thing🙏🙏

**Comment by MuhXd** [comment]
!accept
